# Generated by Django 4.2.11 on 2024-10-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='alt',
            field=models.TextField(default='Capa', help_text='Insira uma descrição da capa para melhorar a acessibilidade.', max_length=1000, verbose_name='Texto alternativo'),
            preserve_default=False,
        ),
    ]
